name: Football Market Projection

on:
  workflow_dispatch:
    inputs:
      match_id:
        description: 'ID del Partido (Copiado del buscador)'
        required: true

jobs:
  predict:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Prediction
        env:
          THESTATSAPI_KEY: ${{ secrets.THESTATSAPI_KEY }}
          ISPORTSAPI_KEY: ${{ secrets.ISPORTSAPI_KEY }}
          MATCH_ID: ${{ github.event.inputs.match_id }}
        run: python main.py
